# Generated by Django 5.0.7 on 2024-07-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_store_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='task',
            new_name='task_name',
        ),
    ]
